server:
  port: 7000
spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL92Dialect
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5439/ticketing-users
    username: postgres
    password: admin

  rabbitmq:
    password: guest
    username: guest
    host: localhost
    port: 5672
