server:
  port: 7001
spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL92Dialect
    generate-ddl: true
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5439/ticketing-notifications
    username: postgres
    password: admin
  rabbitmq:
    password: guest
    username: guest
    host: localhost
    port: 5672
